#!/bin/bash

echo "Start env generation"

GENERATED_CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

GENERATED_POSTGRES_PASS="$(base64 /dev/urandom | tr -dC '[:graph:]'  | stdbuf -o0 head --bytes 55)"
GENERATED_REDIS_PASS="$(base64 /dev/urandom | tr -dC '[:graph:]'  | stdbuf -o0 head --bytes 55)"
SECRET_KEY_BASE="$(base64 /dev/urandom | tr -dC '[:graph:]'  | stdbuf -o0 head --bytes 55)"

POSTGRES_FILE=${GENERATED_CWD}/postgres/ENV.sh
REDIS_FILE=${GENERATED_CWD}/redis/ENV.sh
OPENRESTY_FILE=${GENERATED_CWD}/openresty/ENV.sh
GITLAB_FILE=${GENERATED_CWD}/gitlab/ENV.sh
REDMINE_FILE=${GENERATED_CWD}/redmine/ENV.sh

POSTGRES_USER_NAME=postgres
POSTGRES_DATABASE=postgres
POSTGRES_PORT=5432

echo "\
#!/bin/bash

# autogenerated postgres pass
export POSTGRES_PASS=${GENERATED_POSTGRES_PASS}

# postgres user settings
export POSTGRES_USER=${POSTGRES_USER_NAME}

# postgres management database, service will create their own databases
export POSTGRES_DB=${POSTGRES_DATABASE}

# postgres host settings
export POSTGRES_HOST_PORT=${POSTGRES_PORT}

# postgres container settings
export POSTGRES_CONTAINER_NAME=magic-postgres

# this is the internal port of the container
export POSTGRES_CONTAINER_PORT=5432

# postgres language and encoding
export POSTGRES_LANG=en_US.utf8

# the directory the postgres data will be stored in
export PGDATA=/home/data/postgresql

" > ${POSTGRES_FILE}

echo "\
#!/bin/bash

export REDIS_CONTAINER_NAME=magic-redis

export REDIS_USER_NAME=wnwredis

export REDIS_USER_ID=23523

export REDIS_DIR=/home/redis

export REDIS_CONTAINER_PORT=6379

export REDIS_HOST_PORT=6379

# autogenerated redis password
export REDIS_PASS=${GENERATED_REDIS_PASS}
" > ${REDIS_FILE}

echo "\
#!/bin/bash

export OUT_DIR=./out
export SRC_DIR=./src

export OPENRESTY_PATH=/usr/local/openresty/nginx/sbin
export OPENRESTY_VERSION=1.9.7.1
export OPENRESTY_SRC_DIR=${SRC_DIR}/nginx
export OPENRESTY_LUA_SRC_DIR=${SRC_DIR}/lua
export OPENRESTY_HOST_SRC_DIR=${LUA_SRC_DIR}/hosts
export OPENRESTY_SBIN=/usr/local/openresty/nginx/sbin
export OPENRESTY_CONTAINER_NAME=magic-resty
export OPENRESTY_CONTAINER_PORT_80=8080
export OPENRESTY_HOST_PORT_80=80
export OPENRESTY_CONTAINER_PORT_443=4343
export OPENRESTY_HOST_PORT_443=443
" > ${OPENRESTY_FILE}

echo "\
#!/bin/bash

export GITLAB_CONTAINER_NAME=magic-gitlab

export GITLAB_CONTAINER_PORT_80=80
export GITLAB_CONTAINER_PORT_443=443
export GITLAB_CONTAINER_PORT_22=22

export GITLAB_HOSTNAME=gitlab.wiznwit.com
export GITLAB_HOST_PORT_80=80
export GITLAB_HOST_PORT_443=443
export GITLAB_HOST_PORT_22=22
" > ${GITLAB_FILE}

echo "\
#!/bin/bash

export REDMINE_CONTAINER_NAME=magic-redmine
export REDMINE_SECRET_KEY_BASE=${SECRET_KEY_BASE}

export REDMINE_USER=redmine
export REDMINE_GROUP=redmine
export REDMINE_WORKDIR=/usr/src/redmine

export REDMINE_VERSION=3.0.7
export REDMINE_MD5=d37fbcb2f0300821cb14c80dfc87ca87

export REDMINE_CONTAINER_PORT=3000
export REDMINE_HOST_PORT=3000

export REDMINE_RAILS_ENV=production

# autogenerated postgres pass
export POSTGRES_PASS=${GENERATED_POSTGRES_PASS}

# postgres user settings
export POSTGRES_USER=${POSTGRES_USER_NAME}

# postgres management database, service will create their own databases
export POSTGRES_DB=${POSTGRES_DATABASE}

# postgres host settings
export POSTGRES_PORT=${POSTGRES_PORT}
" > ${REDMINE_FILE}

chmod +x ${POSTGRES_FILE}
chmod +x ${REDIS_FILE}
chmod +x ${OPENRESTY_FILE}
chmod +x ${GITLAB_FILE}
chmod +x ${REDMINE_FILE}

source ${POSTGRES_FILE}
source ${REDIS_FILE}
source ${OPENRESTY_FILE}
source ${GITLAB_FILE}
source ${REDMINE_FILE}

echo "finished env generation"
