#!/bin/bash

echo "Start env generation"

GENERATED_CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

GENERATED_POSTGRES_PASS="$(base64 /dev/urandom | tr -dC '[:graph:]'  | stdbuf -o0 head --bytes 55)"
GENERATED_REDIS_PASS="$(base64 /dev/urandom | tr -dC '[:graph:]'  | stdbuf -o0 head --bytes 55)"
GENERATED_GITLAB_DB_PASS="$(base64 /dev/urandom | tr -dC '[:graph:]'  | stdbuf -o0 head --bytes 55)"
GENERATED_REDMINE_DB_PASS="$(base64 /dev/urandom | tr -dC '[:graph:]'  | stdbuf -o0 head --bytes 55)"
SECRET_KEY_BASE="$(base64 /dev/urandom | tr -dC '[:graph:]'  | stdbuf -o0 head --bytes 55)"

if [ -f "./GITLAB_SECRETS_DB_KEY_BASE" ]; then
  GITLAB_SECRETS_DB_KEY_BASE=$(cat ./GITLAB_SECRETS_DB_KEY_BASE)
else
  GITLAB_SECRETS_DB_KEY_BASE="$(base64 /dev/urandom | tr -dC '[:graph:]'  | stdbuf -o0 head --bytes 55)"
  echo $GITLAB_SECRETS_DB_KEY_BASE >> ./GITLAB_SECRETS_DB_KEY_BASE
fi

POSTGRES_FILE=${GENERATED_CWD}/postgres/ENV.sh
REDIS_FILE=${GENERATED_CWD}/redis/ENV.sh
OPENRESTY_FILE=${GENERATED_CWD}/openresty/ENV.sh
GITLAB_FILE=${GENERATED_CWD}/gitlab/ENV.sh
REDMINE_FILE=${GENERATED_CWD}/redmine/ENV.sh
REDMINE_CONFIG_DIR=${GENERATED_CWD}/redmine/config
REDMINE_DB_CONFIG_FILE=${REDMINE_CONFIG_DIR}/database.yml
REDMINE_SECRET_CONFIG_FILE=${REDMINE_CONFIG_DIR}/secret.yml
REDMINE_RAILS_ENV=production

POSTGRES_USER_NAME=postgres
POSTGRES_DATABASE=postgres
POSTGRES_PORT=5432

GITLAB_HOST_PORT=8888
REDMINE_HOST_PORT=8889
echo "\
#!/bin/bash

# autogenerated postgres pass
export SU_PASS=${GENERATED_POSTGRES_PASS}

# postgres user settings
export SU_USER=${POSTGRES_USER_NAME}

# postgres management database, service will create their own databases
export DB=${POSTGRES_DATABASE}

# postgres host settings
export HOST_PORT=${POSTGRES_PORT}

# postgres container settings
export CONTAINER_NAME=magic-postgres

# this is the internal port of the container
export CONTAINER_PORT=5432

# postgres language and encoding
export LANG=en_US.utf8

# the directory the postgres data will be stored in
export PGDATA=/home/data/postgresql

export GITLAB_DB_USER=gitlab
export GITLAB_DB_PASS=${GENERATED_GITLAB_DB_PASS}
export GITLAB_DB_NAME=gitlabhq_production

export REDMINE_DB_USER=redmine
export REDMINE_DB_PASS=${GENERATED_REDMINE_DB_PASS}
export REDMINE_DB_NAME=redmine_production


" > ${POSTGRES_FILE}
echo "wrote $POSTGRES_FILE"

echo "\
#!/bin/bash

export CONTAINER_NAME=magic-redis

export USER_NAME=wnwredis

export USER_ID=23523

export DIR=/home/redis

export CONTAINER_PORT=6379

export HOST_PORT=6379

# autogenerated redis password
export PASS=${GENERATED_REDIS_PASS}
" > ${REDIS_FILE}
echo "wrote $REDIS_FILE"

echo "\
#!/bin/bash

export OUT_DIR=./out
export SRC_DIR=./src

export EXPORT_PATH=/usr/local/openresty/nginx/sbin
export VERSION=1.9.7.1
export SRC_DIR=${SRC_DIR}/nginx
export LUA_SRC_DIR=${SRC_DIR}/lua
export HOST_SRC_DIR=${LUA_SRC_DIR}/hosts
export SBIN=/usr/local/openresty/nginx/sbin
export CONTAINER_NAME=magic-resty
export CONTAINER_PORT_80=8080
export HOST_PORT_80=80
export CONTAINER_PORT_443=443
export HOST_PORT_443=4343
" > ${OPENRESTY_FILE}
echo "wrote ${OPENRESTY_FILE}"

echo "\
#!/bin/bash

export CONTAINER_NAME=magic-gitlab

export CONTAINER_PORT_80=80
export CONTAINER_PORT_443=443
export CONTAINER_PORT_22=22

export HOSTNAME=gitlab.wiznwit.com
export HOST_PORT_80=$GITLAB_HOST_PORT
export HOST_PORT_443=443
export HOST_PORT_22=22

export GITLAB_DB_USER=gitlab
export GITLAB_DB_PASS=${GENERATED_GITLAB_DB_PASS}
export GITLAB_DB_NAME=gitlabhq_production

" > ${GITLAB_FILE}
echo "wrote $GITLAB_FILE"

echo "\
#!/bin/bash
export HOSTNAME=redmine.wiznwit.com

export CONTAINER_NAME=magic-redmine
export SECRET_KEY_BASE=${SECRET_KEY_BASE}

export POSTGRES_CONTAINER_NAME=magic-postgres

export USER=redmine
export GROUP=redmine
export WORKDIR=/usr/src/redmine

export HOST_PORT=$REDMINE_HOST_PORT

export REDMINE_DB_USER=redmine
export REDMINE_DB_PASS=${GENERATED_REDMINE_DB_PASS}
export REDMINE_DB_NAME=redmine_production
" > ${REDMINE_FILE}
echo "wrote $REDMINE_FILE"


echo "finished env generation"
