#!/bin/bash

export REDIS_CONTAINER_NAME=magic-redis

export REDIS_USER_NAME=wnwredis

export REDIS_USER_ID=23523

export REDIS_DIR=/home/redis

export REDIS_CONTAINER_PORT=6379

export REDIS_HOST_PORT=6379

# autogenerated redis password
export REDIS_PASS=UJRVMJBknTLuFdFWRHgMdi2jPZ1eMU0iUOA3MQm09iRUY0IyvjQzWR9

